### PR TITLE
docfix

### PR DESCRIPTION
**Pull request by MasonProtter**
I suspect you meant to write "often more efficient" not "often less efficient" here

### CODE REVIEW

**Comment by LilithHafner** [comment]
As of now, it is typically less efficient to compile a permutation and apply it once than it is to apply it directly. Perhaps it could be more clear that the current wording is intentional.

**Comment by MasonProtter** [comment]
Oh I get it now. Maybe you could instead say "Often less efficient unless you will reuse the compiled result" or something.

**Comment by LilithHafner** [comment]
If this looks good to you, I'm ready to merge. Thank you for making this more clear.

**Comment by MasonProtter** [comment]
Yeah looks good!

**Pull request merged**
